version: 2

multi-ecosystem-groups:
  monthly-maintenance:
    schedule:
      interval: monthly
    labels:
      - dependencies

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: monthly-maintenance
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: cargo
    directory: /src-tauri
    patterns:
      - "*"
    multi-ecosystem-group: monthly-maintenance
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: monthly-maintenance
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
